---
- name: install commonly used packages
  apt: 
    name: "{{ item }}"
    state: "present"
    update_cache: true
    install_recommends: False
  with_items: 
    - curl
    - unzip
    - jq
    - ca-certificates
    - resolvconf
    - dnsmasq-base
    - dnsmasq
    - dnsutils

- name: configure dnsmasq
  copy: src=dnsmasq-consul.conf dest=/etc/dnsmasq.d/consul.conf

- name: reload dnsmasq
  systemd: name=dnsmasq state=reloaded