---
- name: download nomad binary
  get_url:
    url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    checksum: "{{ nomad_checksum }}"
    dest: "/tmp/nomad_{{ nomad_version }}.zip"

- name: install nomad binary
  unarchive:
    remote_src: "yes"
    src: "/tmp/nomad_{{ nomad_version }}.zip"
    dest: "/usr/local/bin"

- name: remove nomad archive
  file:
    path: "/tmp/nomad_{{ nomad_version }}.zip"
    state: "absent"

- name: create nomad config dir
  file:
    path: "/etc/nomad.d"
    state: "directory"

- name: configure nomad
  template: src=config.hcl.j2 dest=/etc/nomad.d/default.hcl

- name: install systemd unit for nomad
  template: src=nomad.service.j2 dest=/etc/systemd/system/nomad.service

- name: start nomad service
  systemd: state=started name=nomad daemon_reload=yes