---
- hosts: all
  become: yes
  become_method: sudo
  roles:
   - role: common
   - role: docker
   - role: consul
   - role: vault
   - role: nomad-server
   - role: terraform
   - role: nomad-client
